// 3 container app, db, dbtool container das muss ich einbinden

version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: passord
      MYSQL_DATABASE: slala
    ports:
      - "3306:3306"

  dbtool:
    image: adminer:latest
    ports:
      - "8085:80"
    depends_on:
     - db
